var types =
{ abstract: false,
  audiovisual: 'Audiovisual material',
  audio: 'Audiovisual material',
  database: undefined,
  ancient: undefined,
  journalArticle: 'Journal article',
  artwork: 'Artwork',
  bill: undefined,
  blogPost: 'Internet',
  book: 'Book',
  bookSection: 'Book chapter',
  case: undefined,
  chart: undefined,
  classical: undefined,
  software: false,
  proceedings: 'Conference proceedings',
  paper: 'Conference proceedings',
  catalog: undefined,
  data: undefined,
  webdb: undefined,
  dictionaryEntry: 'Book chapter',
  dissertation: 'Dissertation',
  document: 'Book',
  editorial: 'Editorial',
  ebook: undefined,
  echapter: undefined,
  collection: 'Edited book',
  earticle: 'Journal Article',
  internet: 'Internet',
  encyclopediaArticle: 'Book chapter',
  email: 'Personal communication',
  equation: false,
  figure: false,
  generic: false,
  government: false,
  grant: false,
  hearing: false,
  interview: 'Journal article',
  inpress: 'In press',
  journal: 'book',
  legal: false,
  letter: 'Letter',
  note: 'Letter',
  manuscript: 'Book',
  map: 'Map',
  magazineArticle: 'Journal article',
  movie: 'Audiovisual material',
  multimedia: 'Internet',
  music: false,
  newspaperArticle: 'Newspaper article',
  podcast: 'Internet',
  pamphlet: 'Letter',
  patent: 'patent',
  personal: 'Personal communication',
  radioBroadcast: 'Audiovisual material',
  presentation: false,
  report: 'Journal article',
  review: 'Review',
  serial: undefined,
  slide: false,
  sound: undefined,
  standard: undefined,
  statute: false,
  thesis: 'Dissertation',
  tvBroadcast: 'Audiovisual material',
  video: 'Audiovisual material',
  webpage: 'Internet'
};


var fields =
{ id: 'id',
  type: 'type',
  key: 'user1',
  accessDate: 'user20',
  abstract: 'abstract',
  authors: 'authors',
  authorTranslated: 'user9',
  applicationNumber: false,
  attachments: 'attachments',
  blogTitle: 'journal',
  bookTitle: 'volume',
  collections: 'groups',
  conferenceName: 'journal',
  callNumber: 'user5',
  date: 'date',
  dateAdded: 'added',
  doi: 'user17',
  edition: 'user2',
  editors: 'editors',
  issue: 'issue',
  isbn: 'user6',
  issn: 'user6',
  institution: 'publisher',
  journal: 'journal',
  keywords: 'keywords',
  language: 'user7',
  place: 'location',
  notes: 'notes',
  numberOfVolumes: 'user13',
  numPages: 'user13',
  originalPublication: 'user11',
  pages: 'pages',
  publisher: 'publisher',
  pubmedId: 'user18',
  reportNumber: 'issue',
  reprintEdition: 'user12',
  startPage: false,
  endPage: false,
  title: 'title',
  title2: 'title2',
  titleTranslated: 'user10',
  translator: 'user3',
  url: 'url',
  university: 'publisher',
  websiteTitle: 'journal',
  volume: "volume",
  abstractNote: false,
  archive: false,
  artworkSize: false,
  assignee: false,
  billNumber: false,
  caseName: false,
  code: false,
  codeNumber: false,
  codePages: false,
  codeVolume: false,
  committee: false,
  company: false,
  country: false,
  court: false,
  DOI: false,
  dateDecided: false,
  dateEnacted: false,
  dictionaryTitle: false,
  distributor: false,
  docketNumber: false,
  documentNumber: false,
  encyclopediaTitle: false,
  episodeNumber: false,
  extra: false,
  audioFileType: false,
  filingDate: false,
  firstPage: false,
  audioRecordingFormat: false,
  videoRecordingFormat: false,
  forumTitle: false,
  genre: false,
  history: false,
  issueDate: false,
  issuingAuthority: false,
  journalAbbreviation: false,
  label: false,
  programmingLanguage: false,
  legalStatus: false,
  legislativeBody: false,
  libraryCatalog: false,
  archiveLocation: false,
  interviewMedium: false,
  artworkMedium: false,
  meetingName: false,
  nameOfAct: false,
  network: false,
  patentNumber: false,
  postType: false,
  priorityNumbers: false,
  proceedingsTitle: false,
  programTitle: false,
  publicLawNumber: false,
  publicationTitle: false,
  references: false,
  reportType: false,
  reporter: false,
  reporterVolume: false,
  rights: false,
  runningTime: false,
  scale: false,
  section: false,
  series: false,
  seriesNumber: false,
  seriesText: false,
  seriesTitle: false,
  session: false,
  shortTitle: false,
  studio: false,
  subject: false,
  system: false,
  thesisType: false,
  mapType: false,
  manuscriptType: false,
  letterType: false,
  presentationType: false,
  versionNumber: false,
  websiteType: false,
  custom1: 'user4',
  custom2: 'user8',
  custom3: 'user14',
  custom4: 'user15',
  custom5: 'user16',
  custom6: 'user19',
  syncId: 'user20'
};


module.exports = {
  fields : fields,
  types  : types
};
