// The following data maps a generic type to the specific applications' types
// @todo: BibTeX; types that are commented out.
var types = {
  //"abstract"    : { RIS: "ABST", label: "Abstract", zotero: false, bookends: false },
  //"audiovisual" : { RIS: "ADVS", bookends: "Audiovisual material", zotero: false, label : "Audiovisual material" } ,
  //"audio"       : { RIS: "ADVS", bookends: "Audiovisual material", zotero: "audioRecording",  label: "Audio Recording"},
  //"database"    : { RIS : "AGGR", label : "Aggregated Database" },
  //"ancient"     : { RIS: "ANCIENT", zotero: false, label : "Ancient Text"} ,
  "journalArticle" : { RIS : "JOUR", bookends : "Journal article", label : "Journal Article"},
  //"artwork"     : { RIS: "ART", bookends: "Artwork", label : "Artwork" },
  "bill"        : { RIS : "BILL", label : "Bill"},
  "blogPost"    : { RIS : "BLOG", bookends: "Internet", label : "Blog Post" },
  "book"        : { RIS : "BOOK", bookends : "Book", label : "Book (Monograph)"},
  "bookSection" : { RIS : "CHAP", bookends: "Book chapter", label : "Book Section"},
  "case"        : { RIS : "CASE", label : "Case"},
  //"chart"       : { RIS : "CHART", zotero: false, label : "Chart"},
  //"classical"   : { RIS : "CLSWK", zotero: false, label : "Classical Work"},
  //"software"    : { RIS : "COMP", bookends: false, zotero: "computerProgram", label : "Computer program"},
  "proceedings" : { RIS : "CONF", bookends: "Conference proceedings", zotero: "book", label : "Conference proceedings"},
  "paper"       : { RIS : "CPAPER", bookends: "Conference proceedings", zotero: "conferencePaper", label : "Conference paper"},
  //"catalog"     : { RIS : "CTLG", zotero: "book", label : "Catalog"},
  //"data"        : { RIS : "DATA", zotero: false, label : "Data file"},
  //"web-db"      : { RIS : "DBASE", zotero: false, label : "Online Database"},
  //"dictionaryEntry" : { RIS : "DICT", bookends: "Book chapter", label : "DictionaryEntry"},
  "dissertation" : { RIS : "THES", zotero: "thesis", bookends: "Dissertation", label : "Dissertation"},
  "document"    :  { RIS : "UNPB", bookends: "Book", label : "Unpublished Document"},
  //"editorial"   : { RIS : "NEWS", zotero : "newspaperArticle", bookends: "Editorial", label : "Editorial"},
  //"ebook"       : { RIS : "EBOOK", zotero: "book", label : "Electronic Book"},
  //"echapter"    : { RIS : "ECHAP", zotero: "bookSection", label : "Electronic Book Section"},
  "collection"  : { RIS : "EDBOOK", zotero: "book", bookends: "Edited book", label : "Edited Book"},
  //"earticle"    : { RIS : "EJOUR", zotero: "journalArticle", bookends: "Journal Article", label : "Electronic Article"},
  "internet"     : { RIS : "ELEC", bookends : "Internet", zotero: "webpage", label : "Internet Resource"},
  //"encyclopediaArticle" : { RIS : "ENCYC", bookends: "Book chapter", label : "Encyclopedia Article"},
  //"email"       : { RIS : "ICOMM", bookends: "Personal communication", label : "Email"},
  //"equation"    : { RIS : "EQUA", bookends : false, zotero: false, label : "Equation"},
  //"figure"      : { RIS : "FIGURE", bookends : false, zotero: false, label : "Figure"},
  //"generic"     : { RIS : "GEN", bookends : false, zotero: false, label : "Generic"},
  //"government"  : { RIS : "GOVDOC", bookends : false, zotero: false, label : "Government Document"},
  //"grant"       : { RIS : "GRANT", bookends : false, zotero: false, label : "Grant"},
  //"hearing"     : { RIS : "HEAR", bookends : false, label : "Hearing"},
  "interview"   : { RIS : "JOUR", bookends : "Journal article", label : "Interview"},
  "inpress"     : { RIS : "INPR", bookends: "In press", label : "In Press"},
  "journal"     : { RIS : "JFULL", bookends: "book", zotero : "book", label : "Journal (full)"},
  //"legal"       : { RIS : "LEGAL", bookends : false, zotero : "bill", label : "Legal Rule or Regulation"},
  //"letter"      : { RIS : "UNPB", bookends : "Letter", label : "Letter"},
  //"note"        : { RIS : "UNPB", bookends : "Letter", label : "Note"},
  "manuscript"  : { RIS : "MANSCPT", bookends: "Book", label : "Manuscript"},
  //"map"         : { RIS : "MAP", bookends : "Map", label : "Map"},
  "magazineArticle" : { RIS : "MGZN", bookends : "Journal article", label : "Magazine article"},
  //"movie"       : { RIS : "MPCT", bookends: "Audiovisual material", zotero: "movie", label : "Motion Picture"},
  //"multimedia"   : { RIS : "MULTI", bookends: "Internet", label : "Online Multimedia"},
  //"music"       : { RIS : "MUSIC", bookends : false, zotero: false, label : "Music Score"},
  "newspaperArticle" : { RIS : "NEWS", bookends : "Newspaper article", label : "Newspaper Article"},
  "podcast"     : { RIS : "BLOG", bookends: "Internet", label : "Podcast" },
  //"pamphlet"    : { RIS : "UNPB", bookends : "Letter", zotero : "document", label : "Pamphlet"},
  //"patent"      : { RIS : "PAT", bookends : "patent",  label : "Patent"},
  //"personal"    : { RIS : "PCOMM", bookends : "Personal communication", zotero: "letter", label : "Personal Communication"},
  //"radioBroadcast" : { RIS: "ADVS", bookends: "Audiovisual material", label: "Radio Broadcast"},
  //"presentation" : { RIS : "SLIDE", bookends: false, label : "Presentation"},
  "report"      : { RIS : "RPRT", bookends: "Journal article", label : "Report"},
  //"review"      : { RIS : "JOUR", bookends : "Review", zotero : "journalArticle", label : "Review"},
  //"serial"      : { RIS : "SER", label : "Serial publication"},
  //"slide"       : { RIS : "SLIDE", bookends: false, zotero: false, label : "Slide"},
  //"sound"       : { RIS : "SOUND", label : "Sound recording"},
  //"standard"    : { RIS : "STAND", label : "Standard"},
  "statute"     : { RIS : "STAT", bookends: false, label : "Statute"},
  "thesis"      : { RIS : "THES", bookends: "Dissertation", label : "Thesis"},
  //"tvBroadcast" : { RIS : "VIDEO", label : "TV Broadcast", bookends: "Audiovisual material" },
  //"video"       : { RIS : "VIDEO", label : "Video recording", bookends: "Audiovisual material", zotero: "videoRecording"},
  "webpage"     : { RIS : "ELEC", bookends : "Internet", label : "Webpage"},
};

module.exports = types;
